Update nc-create-xe-native-vrf-22-ydk.py
fixing typo which causes following error
```
2019-01-22 17:37:50,446 - ydk - INFO - Connected to csr1kv1 on port 830 using ssh with timeout of -1
Traceback (most recent call last):
  File "nc-create-xe-native-vrf-22-ydk.py", line 93, in <module>
    config_native(native)  # add object configuration
  File "nc-create-xe-native-vrf-22-ydk.py", line 52, in config_native
    import_ = ipv6.route_target.Import_()
AttributeError: 'RouteTarget' object has no attribute 'Import_'
2019-01-22 17:37:50,758 - ydk - INFO - Disconnected from device
```